language: php
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?$/"
php:
- 7.1
- 7.2
- 7.3
env:
- WP_VERSION=latest WP_MULTISITE=1 TRAVIS_NODE_VERSION="8"
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.yarn-cache"
  - node_modules
  - vendor
before_install:
- composer self-update
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
- export PATH=$HOME/.yarn/bin:$PATH && travis_retry curl -o- -L https://yarnpkg.com/install.sh
  | bash
install:
- node -v && yarn -V
- travis_retry yarn
- composer install -o --prefer-dist --no-interaction
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv
  config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- yarn run build:production
- yarn run rmdist
- vendor/bin/phpunit --configuration=phpunit.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml .
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- yarn run build:production
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: tczyEOnhtKDGMWnuMFx9XgL+lt/ijtqRqInmApq5zUMfnSsuVFPYWS/KfJvlDFTMY4+Ulzc7ldkbBgi20mLFfdT59NOIQFTEJxIL1RfqCaqAIsmgcO+RORo9gc9GxsYJHHwcsqiVvZ7HSEbPEUIicN2QLyA04ebcFmw/QVBa5NypizY+g93hl94qO78zqFgBDPCkK8r6nu+ubvJimSaXpMf9WDaeduD4X2LrjpEhDDZLjt6k1bsHXM2RU1q7Ww2wXQOZL7IStV0hLSXbN0BoscYhOX71Fo7IFvuveYfonpket2YftmcihgHDszUf0Ofg99qp10IcV7KcQJrF3G18v2v622+xfybKEg6UveiAGHlYtMQiIigNgLJC1kn/gp34Y6kti237veYhVaCfNDJ2Ecr3XDvb2htj9QGp2bOxz6bkJ7q3DyLb8FdTj5Ri0rJSxNH/XxXSBEAw68nBcSRBAjX6DpGYcljTaZwFoI7aO+jc0gE5FRGplxFdEjTEB4+ZW9c67A7+G42uBpF5AkjgI1mpu2p699XULKKfFZOpyQh6p7uR6zDIzbQzbPZlQy7IBTuBeky2+U/BUku+aiksKMNhYxbWz6XUgLFq3JkdOfoU2Z8dEuFSCthHZMZ5ZEHY+28G240wxNZR949n3iBy9/ptTVAskSNj0K2b87e5wVU=
  file: bcc-sage-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: BCcampus/bcc-sage
    branch: dev
